spring:
  jpa:
    database: POSTGRESQL
#    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bill_service_database
    username: postgres
    password: zalupa
    driver-class-name: org.postgresql.Driver
